# 拉取基础镜像
FROM fantito/jdk11-maven-git:latest
# 把hello_springboot.jar添加到容器里，并重命名为app.jar
# 因为hello_springboot.jar和Dockerfile在同一个目录下，所以只写文件名即可
#ADD ./target/cms-admin-pro-0.2.0-SNAPSHOT.jar app.jar
#EXPOSE 9292

# 执行命令，此处运行app.jar
# RUN bash -c 'touch /app.jar'
# ENTRYPOINT ["java","-jar","app.jar"]